#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
#ifndef ONFIDO_SWIFT_H
#define ONFIDO_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Onfido",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)


@class UIColor;
@class ONBackgroundColor;
@class ONCaptureSuccessColors;
@class NSString;

SWIFT_CLASS_NAMED("Appearance")
@interface ONAppearance : NSObject
@property (nonatomic, strong) UIColor * _Nonnull primaryColor;
@property (nonatomic, strong) UIColor * _Nonnull primaryTitleColor;
@property (nonatomic, strong) UIColor * _Nullable secondaryTitleColor;
@property (nonatomic, strong) UIColor * _Nonnull primaryBackgroundPressedColor;
@property (nonatomic, strong) UIColor * _Nonnull secondaryBackgroundPressedColor;
@property (nonatomic, strong) ONBackgroundColor * _Nonnull backgroundColor;
@property (nonatomic, strong) ONCaptureSuccessColors * _Nonnull captureSuccessColors;
@property (nonatomic, copy) NSString * _Nullable fontRegular;
@property (nonatomic, copy) NSString * _Nullable fontBold;
@property (nonatomic) CGFloat buttonCornerRadius;
- (void)setUserInterfaceStyle:(UIUserInterfaceStyle)style;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS_NAMED("BackgroundColor")
@interface ONBackgroundColor : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLightColor:(UIColor * _Nonnull)lightColor darkColor:(UIColor * _Nonnull)darkColor OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Onfido25BaseDocumentConfiguration")
@interface BaseDocumentConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, CancellationReason, open) {
  CancellationReasonUserExit = 0,
  CancellationReasonDeniedConsent = 1,
  CancellationReasonRequiredNFCFlowNotCompleted = 2,
};


SWIFT_CLASS_NAMED("CaptureSuccessColors")
@interface ONCaptureSuccessColors : NSObject
@property (nonatomic, strong) UIColor * _Nonnull borderColor;
@property (nonatomic, strong) UIColor * _Nonnull tickViewImageTintColor;
@property (nonatomic, strong) UIColor * _Nonnull tickViewBackgroundColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CertificatePinningConfiguration")
@interface ONCertificatePinningConfiguration : NSObject
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull hashes;
- (nullable instancetype)initWithHashes:(NSArray<NSString *> * _Nonnull)hashes error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



typedef SWIFT_ENUM(NSInteger, DocumentFormat, open) {
  DocumentFormatCard = 0,
  DocumentFormatFolded = 1,
};


SWIFT_CLASS_NAMED("DocumentMetadata")
@interface ONDocumentMetadata : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull side;
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
@property (nonatomic, readonly, copy) NSString * _Nullable issuingCountry;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, ONDocumentPages, "DocumentPages", open) {
  ONDocumentPagesSingle = 1,
  ONDocumentPagesFrontAndBack = 2,
};

@class ONDocumentSideResult;

SWIFT_CLASS_NAMED("DocumentResult")
@interface ONDocumentResult : NSObject
@property (nonatomic, readonly, strong) ONDocumentSideResult * _Nonnull front;
@property (nonatomic, readonly, strong) ONDocumentSideResult * _Nullable back;
@property (nonatomic, readonly, copy) NSString * _Nonnull typeSelected;
@property (nonatomic, readonly, copy) NSString * _Nullable countrySelected;
@property (nonatomic, readonly, copy) NSString * _Nullable nfcMediaId;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS_NAMED("DocumentSideResult")
@interface ONDocumentSideResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class DocumentConfigBuilder;

SWIFT_CLASS_NAMED("DocumentTypeConfig")
@interface ONDocumentTypeConfig : NSObject
+ (DocumentConfigBuilder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ONPassportConfiguration;
@class ONDrivingLicenceConfiguration;
@class ONNationalIdentityConfiguration;
@class ONResidencePermitConfiguration;
@class ONVisaConfiguration;
@class ONWorkPermitConfiguration;
@class ONGenericDocumentConfiguration;

SWIFT_CLASS("_TtCC6Onfido18DocumentTypeConfig21DocumentConfigBuilder")
@interface DocumentConfigBuilder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// show custom document from selectable documents types
/// \param selectableDocumentTypes customize the document types appears in the select document type screen
/// @[@(SelectableDocumentTypePassport), @(SelectableDocumentTypeDrivingLicence) ]
///
///
/// returns:
/// DocumentConfigBuilder
- (DocumentConfigBuilder * _Nonnull)withDocumentStepWithSelectableDocumentTypes:(NSArray * _Nonnull)selectableDocumentTypes;
- (DocumentConfigBuilder * _Nonnull)withPassportWithConfig:(ONPassportConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withDrivingLicenceWithConfig:(ONDrivingLicenceConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withNationalIdentityCardWithConfig:(ONNationalIdentityConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withResidencePermitWithConfig:(ONResidencePermitConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withVisaWithConfig:(ONVisaConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withWorkPermitWithConfig:(ONWorkPermitConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withGenericWithConfig:(ONGenericDocumentConfiguration * _Nullable)config;
- (ONDocumentTypeConfig * _Nullable)buildAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("DrivingLicenceConfiguration")
@interface ONDrivingLicenceConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithDocumentFormat:(enum DocumentFormat)documentFormat country:(NSString * _Nullable)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL_NAMED("EncryptedBiometricTokenHandler")
@protocol ONEncryptedBiometricTokenHandler
- (void)onTokenRequestedWithCustomerUserHash:(NSString * _Nonnull)customerUserHash completion:(void (^ _Nonnull)(NSString * _Nonnull))completion;
- (void)onTokenGeneratedWithCustomerUserHash:(NSString * _Nonnull)customerUserHash encryptedBiometricToken:(NSString * _Nonnull)encryptedBiometricToken;
@end

@class ONEnterpriseFeaturesBuilder;

SWIFT_CLASS_NAMED("EnterpriseFeatures")
@interface ONEnterpriseFeatures : NSObject
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
+ (ONEnterpriseFeaturesBuilder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIImage;

SWIFT_CLASS_NAMED("Builder")
@interface ONEnterpriseFeaturesBuilder : NSObject
- (ONEnterpriseFeaturesBuilder * _Nonnull)withHideOnfidoLogo:(BOOL)hideOnfidoLogo;
- (ONEnterpriseFeaturesBuilder * _Nonnull)withCobrandingText:(NSString * _Nonnull)cobrandingText;
- (ONEnterpriseFeaturesBuilder * _Nonnull)withCobrandingLogo:(UIImage * _Nonnull)cobrandingLogoLightMode cobrandingLogoDarkMode:(UIImage * _Nonnull)cobrandingLogoDarkMode;
- (ONEnterpriseFeaturesBuilder * _Nonnull)withDisableMobileSdkAnalytics:(BOOL)disableMobileSdkAnalytics;
- (ONEnterpriseFeatures * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Minimal capture UI for documents and faces with built-in validation
SWIFT_CLASS("_TtC6Onfido5Event")
@interface Event : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull properties;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum ONFaceResultVariant : NSInteger;

SWIFT_CLASS_NAMED("FaceResult")
@interface ONFaceResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly) enum ONFaceResultVariant variant;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, ONFaceResultVariant, "FaceResultVariant", open) {
  ONFaceResultVariantPhoto = 0,
  ONFaceResultVariantVideo = 1,
  ONFaceResultVariantMotion = 2,
};

@class Builder;

SWIFT_CLASS_NAMED("FaceStepVariantConfig")
@interface ONFaceStepVariantConfig : NSObject
+ (Builder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ONVideoStepConfiguration;
@class ONPhotoStepConfiguration;
@class ONMotionStepConfiguration;

SWIFT_CLASS("_TtCC6Onfido21FaceStepVariantConfig7Builder")
@interface Builder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (Builder * _Nonnull)withVideoCaptureWithConfig:(ONVideoStepConfiguration * _Nullable)config;
- (Builder * _Nonnull)withPhotoCaptureWithConfig:(ONPhotoStepConfiguration * _Nullable)config;
- (Builder * _Nonnull)withMotionWithConfig:(ONMotionStepConfiguration * _Nullable)config;
- (ONFaceStepVariantConfig * _Nullable)buildAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("GenericDocumentConfiguration")
@interface ONGenericDocumentConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithCountry:(NSString * _Nullable)country OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithTitle:(NSString * _Nonnull)title subtitle:(NSString * _Nullable)subtitle country:(NSString * _Nullable)country pages:(enum ONDocumentPages)pages error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL_NAMED("MediaResult")
@protocol ONMediaResult
@end

@class ONMediaFile;

SWIFT_CLASS_NAMED("LivenessResult")
@interface ONLivenessResult : NSObject <ONMediaResult>
@property (nonatomic, readonly, strong) ONMediaFile * _Nonnull file;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL_NAMED("MediaCallback")
@protocol ONMediaCallback
- (void)onMediaCapturedWithResult:(id <ONMediaResult> _Nonnull)result;
@end


SWIFT_CLASS_NAMED("MediaDocumentResult")
@interface ONMediaDocumentResult : NSObject <ONMediaResult>
@property (nonatomic, readonly, strong) ONDocumentMetadata * _Nonnull metadata;
@property (nonatomic, readonly, strong) ONMediaFile * _Nonnull file;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSData;

SWIFT_CLASS_NAMED("MediaFile")
@interface ONMediaFile : NSObject
@property (nonatomic, readonly, copy) NSData * _Nonnull fileData;
@property (nonatomic, readonly, copy) NSString * _Nonnull fileName;
@property (nonatomic, readonly, copy) NSString * _Nonnull fileType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS_NAMED("MotionStepConfiguration")
@interface ONMotionStepConfiguration : NSObject
- (nonnull instancetype)initWithShowIntro:(BOOL)showIntro OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRecordAudio:(BOOL)recordAudio OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithIsTestEnv:(BOOL)isTestEnv OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithShowIntro:(BOOL)showIntro recordAudio:(BOOL)recordAudio OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithShowIntro:(BOOL)showIntro isTestEnv:(BOOL)isTestEnv OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRecordAudio:(BOOL)recordAudio isTestEnv:(BOOL)isTestEnv OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithShowIntro:(BOOL)showIntro recordAudio:(BOOL)recordAudio isTestEnv:(BOOL)isTestEnv OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, ONNFCConfiguration, "NFCConfiguration", open) {
  ONNFCConfigurationOff = 0,
  ONNFCConfigurationOptional = 1,
  ONNFCConfigurationRequired = 2,
};


SWIFT_CLASS_NAMED("NationalIdentityConfiguration")
@interface ONNationalIdentityConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithDocumentFormat:(enum DocumentFormat)documentFormat country:(NSString * _Nullable)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSDate;

/// Address object as defined by the Onfido API
SWIFT_CLASS_NAMED("ONAddressResult")
@interface ONAddressResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable flatNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable buildingNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable buildingName;
@property (nonatomic, readonly, copy) NSString * _Nullable street;
@property (nonatomic, readonly, copy) NSString * _Nullable subStreet;
@property (nonatomic, readonly, copy) NSString * _Nullable town;
@property (nonatomic, readonly, copy) NSString * _Nullable state;
@property (nonatomic, readonly, copy) NSString * _Nullable postcode;
@property (nonatomic, readonly, copy) NSString * _Nullable country;
@property (nonatomic, readonly, copy) NSDate * _Nullable startDate;
@property (nonatomic, readonly, copy) NSDate * _Nullable endDate;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ONFlowConfig;
@class ONWorkflowConfiguration;
@class UIViewController;
@class ONFlowResponse;

/// Objective-C wrapper for OnfidoFlow
SWIFT_CLASS_NAMED("ONFlow")
@interface ONFlow : NSObject
- (nonnull instancetype)initWithFlowConfiguration:(ONFlowConfig * _Nonnull)flowConfiguration;
- (nonnull instancetype)initWithWorkflowConfiguration:(ONWorkflowConfiguration * _Nonnull)workflowConfiguration;
- (BOOL)runFrom:(UIViewController * _Nonnull)viewController animated:(BOOL)flag error:(NSError * _Nullable * _Nullable)error completion:(void (^ _Nullable)(void))completion;
- (BOOL)runFrom:(UIViewController * _Nonnull)viewController presentationStyle:(UIModalPresentationStyle)modalPresentationStyle animated:(BOOL)flag error:(NSError * _Nullable * _Nullable)error completion:(void (^ _Nullable)(void))completion;
- (ONFlow * _Nonnull)withResponseHandler:(void (^ _Nonnull)(ONFlowResponse * _Nonnull))responseHandler;
- (ONFlow * _Nonnull)withResponseHandler:(void (^ _Nonnull)(ONFlowResponse * _Nonnull))responseHandler dismissFlowOnCompletion:(BOOL)dismissFlowOnCompletion;
- (ONFlow * _Nonnull)withEventHandler:(void (^ _Nonnull)(Event * _Nonnull))eventHandler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ONFlowCancellation")
@interface ONFlowCancellation : NSObject
/// Reason why user cancelled the flow
@property (nonatomic, readonly) enum CancellationReason reason;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ONFlowConfigBuilder;

/// Objective-C wrapper for OnfidoConfig struct
/// NOTE: Swift structs are not supported in Objective-C
SWIFT_CLASS_NAMED("ONFlowConfig")
@interface ONFlowConfig : NSObject
+ (ONFlowConfigBuilder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSBundle;

SWIFT_CLASS_NAMED("ONFlowConfigBuilder")
@interface ONFlowConfigBuilder : NSObject
- (void)withSdkToken:(NSString * _Nonnull)sdkToken;
- (void)withSdkToken:(NSString * _Nonnull)sdkToken expireHandler:(void (^ _Nonnull)(void (^ _Nonnull)(NSString * _Nonnull)))expireHandler;
- (void)withMediaCallback:(id <ONMediaCallback> _Nonnull)mediaCallback;
- (void)withWelcomeStep;
- (void)withDocumentStep;
- (void)withDocumentStepOfType:(ONDocumentTypeConfig * _Nonnull)config;
- (void)withGenericDocumentsWithAdditionalTypes:(NSArray<ONGenericDocumentConfiguration *> * _Nonnull)genericConfig;
- (void)withFaceStepOfVariant:(ONFaceStepVariantConfig * _Nonnull)variant;
- (void)withCustomLocalization;
- (void)withCustomLocalizationWithTableName:(NSString * _Nonnull)tableName;
- (void)withCustomLocalizationWithTableName:(NSString * _Nonnull)tableName in:(NSBundle * _Nonnull)bundle;
- (void)withAppearance:(ONAppearance * _Nonnull)appearance;
- (void)withEnterpriseFeatures:(ONEnterpriseFeatures * _Nonnull)enterpriseFeatures;
- (void)withCertificatePinningConfiguration:(ONCertificatePinningConfiguration * _Nonnull)configuration;
- (void)disableNFC SWIFT_DEPRECATED_MSG("Use withNFC() instead");
- (void)withNFC:(enum ONNFCConfiguration)nfc;
- (void)withProofOfAddressStep;
/// Builds ONFlowConfig object
- (ONFlowConfig * _Nullable)buildAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, ONFlowConfigError, "ONFlowConfigError", open) {
  ONFlowConfigErrorMissingSDKToken = 0,
  ONFlowConfigErrorInvalidSDKToken = 1,
  ONFlowConfigErrorMissingSteps = 2,
  ONFlowConfigErrorInvalidDocumentFormatAndCountryCombination = 3,
  ONFlowConfigErrorInvalidCountryCode = 4,
  ONFlowConfigErrorEnterpriseFeaturesNotAuthorized = 5,
  ONFlowConfigErrorSelectedEnterpriseFeatureNotAuthorized = 6,
  ONFlowConfigErrorEnterpriseFeatureProvidedWithMobileToken = 7,
  ONFlowConfigErrorInvalidDocumentTitle = 8,
  ONFlowConfigErrorDuplicateGenericDocument = 9,
  ONFlowConfigErrorInvalidCustomTranslations = 10,
};

typedef SWIFT_ENUM_NAMED(NSInteger, ONFlowError, "ONFlowError", open) {
  ONFlowErrorCameraPermission = 0,
  ONFlowErrorMicrophonePermission = 1,
  ONFlowErrorUpload = 2,
  ONFlowErrorException = 3,
  ONFlowErrorFailedToWriteToDisk = 4,
  ONFlowErrorInvalidImageData = 5,
  ONFlowErrorVersionInsufficient = 6,
  ONFlowErrorStudioTaskAbandoned = 7,
  ONFlowErrorStudioTaskError = 8,
};

@class ONFlowResult;
@class NSError;

SWIFT_CLASS_NAMED("ONFlowResponse")
@interface ONFlowResponse : NSObject
/// The results generated upon a success run of the flow
@property (nonatomic, copy) NSArray<ONFlowResult *> * _Nullable results;
/// The error encountered during the flow if any
@property (nonatomic, strong) NSError * _Nullable error;
/// Reason why user cancelled the flow if any
@property (nonatomic, strong) ONFlowCancellation * _Nullable userCanceled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ONFlowResultType : NSInteger;

SWIFT_CLASS_NAMED("ONFlowResult")
@interface ONFlowResult : NSObject
/// The type of result
@property (nonatomic, readonly) enum ONFlowResultType type;
/// The result object (ONApplicantResult, ONDocumentResult, ONFaceResult)
@property (nonatomic, strong) id _Nonnull result;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Enumeration to list the possible results type generated during the flow
typedef SWIFT_ENUM_NAMED(NSInteger, ONFlowResultType, "ONFlowResultType", open) {
  ONFlowResultTypeDocument = 0,
  ONFlowResultTypeFace = 1,
  ONFlowResultTypeProofOfAddress = 2,
};


/// IdNumber object as defined by the Onfido API
SWIFT_CLASS_NAMED("ONIdNumberResult")
@interface ONIdNumberResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable type;
@property (nonatomic, readonly, copy) NSString * _Nullable value;
@property (nonatomic, readonly, copy) NSString * _Nullable stateCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("PassportConfiguration")
@interface ONPassportConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithCountry:(NSString * _Nullable)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("PhotoStepConfiguration")
@interface ONPhotoStepConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithShowSelfieIntroScreen:(BOOL)showSelfieIntroScreen OBJC_DESIGNATED_INITIALIZER;
@end

@class ONProofOfAddressSideResult;

SWIFT_CLASS_NAMED("ProofOfAddressResult")
@interface ONProofOfAddressResult : NSObject
@property (nonatomic, readonly, strong) ONProofOfAddressSideResult * _Nonnull front;
@property (nonatomic, readonly, strong) ONProofOfAddressSideResult * _Nullable back;
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ProofOfAddressSideResult")
@interface ONProofOfAddressSideResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nullable type;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ResidencePermitConfiguration")
@interface ONResidencePermitConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, SelectableDocumentType, open) {
  SelectableDocumentTypePassport = 0,
  SelectableDocumentTypeDrivingLicence = 1,
  SelectableDocumentTypeIdentityCard = 2,
  SelectableDocumentTypeResidencePermit = 3,
};


SWIFT_CLASS_NAMED("SelfieResult")
@interface ONSelfieResult : NSObject <ONMediaResult>
@property (nonatomic, readonly, strong) ONMediaFile * _Nonnull file;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end















SWIFT_CLASS_NAMED("VideoStepConfiguration")
@interface ONVideoStepConfiguration : NSObject
- (nonnull instancetype)initWithShowIntroVideo:(BOOL)showIntroVideo manualLivenessCapture:(BOOL)manualLivenessCapture OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("VisaConfiguration")
@interface ONVisaConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("WorkPermitConfiguration")
@interface ONWorkPermitConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("WorkflowConfiguration")
@interface ONWorkflowConfiguration : NSObject
- (ONWorkflowConfiguration * _Nonnull)withAppearance:(ONAppearance * _Nonnull)appearance;
- (ONWorkflowConfiguration * _Nonnull)withEnterpriseFeatures:(ONEnterpriseFeatures * _Nonnull)enterpriseFeatures;
- (ONWorkflowConfiguration * _Nonnull)withCustomLocalizationWithTableName:(NSString * _Nonnull)tableName in:(NSBundle * _Nonnull)bundle;
- (ONWorkflowConfiguration * _Nonnull)withMediaCallbackWithMediaCallback:(id <ONMediaCallback> _Nonnull)mediaCallback;
- (ONWorkflowConfiguration * _Nonnull)withTokenExpirationHandlerWithHandler:(void (^ _Nonnull)(void (^ _Nonnull)(NSString * _Nonnull)))handler;
- (ONWorkflowConfiguration * _Nonnull)withEncryptedBiometricTokenHandlerWithHandler:(id <ONEncryptedBiometricTokenHandler> _Nonnull)handler;
- (nonnull instancetype)initWithWorkflowRunId:(NSString * _Nonnull)workflowRunId sdkToken:(NSString * _Nonnull)sdkToken OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
